apiVersion: v1
kind: Service
metadata:
  name: prob-external
  labels:
    app: probe
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: probe
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: probe
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: probe
    spec:
      containers:
      - name: probe
        image: datianshi/kube-probe
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
